language: node_js
node_js:
  - "11"
before_script:
  - npm install
script:
  - npm test
  - npm run lint
  - npx prettier --parser=typescript --tab-width=4 --trailing-comma=all --check *.ts test/*.ts
